# Generated by Django 3.0.6 on 2020-08-19 14:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('bestwish', models.CharField(blank=True, default=None, max_length=350, null=True)),
                ('warningmessage', models.CharField(blank=True, default=None, max_length=550, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 19, 19, 46, 12, 529064))),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Quiz_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writtenquestion', models.CharField(blank=True, default='', max_length=330, null=True)),
                ('imagequestion', models.ImageField(blank=True, default='', null=True, upload_to='pics')),
                ('option1', models.CharField(default='A', max_length=150)),
                ('option2', models.CharField(default='B', max_length=150)),
                ('option3', models.CharField(default='C', max_length=150)),
                ('option4', models.CharField(default='D', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Quiz_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('bestwish', models.CharField(blank=True, default=None, max_length=350, null=True)),
                ('warningmessage', models.CharField(blank=True, default=None, max_length=550, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 19, 19, 46, 12, 544664))),
            ],
        ),
        migrations.CreateModel(
            name='TecherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writtenquestion', models.CharField(blank=True, default='', max_length=330, null=True)),
                ('imagequestion', models.ImageField(blank=True, default='', null=True, upload_to='pics')),
                ('option1', models.CharField(default='A', max_length=150)),
                ('option2', models.CharField(default='B', max_length=150)),
                ('option3', models.CharField(default='C', max_length=150)),
                ('option4', models.CharField(default='D', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmitQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.TextField()),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
