# Generated by Django 3.0.6 on 2020-08-09 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 7, 13, 0, 572013)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='option1',
            field=models.CharField(default='A', max_length=150),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='option2',
            field=models.CharField(default='B', max_length=150),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='option3',
            field=models.CharField(default='C', max_length=150),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='option4',
            field=models.CharField(default='D', max_length=150),
        ),
    ]
