# Generated by Django 3.0.6 on 2020-08-13 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 8, 21, 57, 816448)),
        ),
    ]
