# Generated by Django 3.0.6 on 2020-08-19 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0002_auto_20200819_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 19, 48, 31, 577015)),
        ),
        migrations.AlterField(
            model_name='teacher_quiz_text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 19, 48, 31, 582015)),
        ),
    ]
