# Generated by Django 3.0.6 on 2020-08-09 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0003_auto_20200809_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writtenquestion', models.CharField(blank=True, default=None, max_length=330, null=True)),
                ('imagequestion', models.ImageField(blank=True, default=None, null=True, upload_to='teacher')),
                ('option1', models.CharField(default='A', max_length=150)),
                ('option2', models.CharField(default='B', max_length=150)),
                ('option3', models.CharField(default='C', max_length=150)),
                ('option4', models.CharField(default='D', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='imagequestion',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='writtenquestion',
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 8, 11, 17, 794911)),
        ),
    ]
