# Generated by Django 3.0.6 on 2020-08-13 02:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_news', '0003_auto_20200813_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmit',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 8, 26, 35, 448790)),
        ),
    ]
