# Generated by Django 3.0.6 on 2020-08-13 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0004_auto_20200813_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 8, 26, 38, 945520)),
        ),
    ]
