# Generated by Django 3.0.6 on 2020-08-09 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0004_auto_20200809_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='stdname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 48, 24, 180488)),
        ),
        migrations.AlterField(
            model_name='techerdata',
            name='writtenquestion',
            field=models.CharField(blank=True, default='', max_length=330, null=True),
        ),
    ]
