# Generated by Django 3.0.6 on 2020-09-06 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0008_auto_20200819_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmitquiz',
            name='user',
        ),
        migrations.DeleteModel(
            name='Teacher_Quiz_Questions',
        ),
        migrations.DeleteModel(
            name='Teacher_Quiz_text',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 17, 27, 47, 956305)),
        ),
        migrations.DeleteModel(
            name='StudentSubmitQuiz',
        ),
    ]
