# Generated by Django 3.0.6 on 2020-09-12 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0012_auto_20200912_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 7, 16, 54, 202693)),
        ),
    ]
