# Generated by Django 3.0.6 on 2020-09-12 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0014_auto_20200912_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='stdname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 8, 4, 12, 47660)),
        ),
    ]
