# Generated by Django 3.0.6 on 2020-09-12 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0015_auto_20200912_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='stdname',
        ),
        migrations.RemoveField(
            model_name='stud',
            name='user',
        ),
        migrations.AddField(
            model_name='stud',
            name='student_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stud',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 8, 7, 23, 882633)),
        ),
    ]
