# Generated by Django 3.0.6 on 2020-09-13 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_news', '0016_auto_20200912_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techerdata',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='techerdata',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='techerdata',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='techerdata',
            name='option4',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 9, 59, 4, 526584)),
        ),
    ]
