# Generated by Django 3.0.6 on 2020-08-19 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('mobile_no', models.CharField(blank=True, max_length=222)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagepost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=222)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 19, 19, 46, 12, 529064))),
                ('caption', models.CharField(default=None, max_length=2222)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(default='static/images/john.jpg', upload_to='pics')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videopost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=222)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 19, 19, 46, 12, 529064))),
                ('caption', models.CharField(default=None, max_length=2222)),
                ('utube_video_link', models.CharField(max_length=2222)),
            ],
        ),
    ]
